### PR TITLE
Cleanups for bpf-examples V2

### PR DESCRIPTION
**Pull request by netoptimizer**
This PR replace #6

### CODE REVIEW

**Comment by netoptimizer** [comment]
Dropped the patch that @tohojo didn't like in #6

**Comment by tohojo** [comment]
Hmm, okay, but if we're installing the libbpf headers to a different directory, shouldn't it be under headers/ instead of under lib/ ? :)

**Comment by netoptimizer** [comment]
> Hmm, okay, but if we're installing the libbpf headers to a different directory, shouldn't it be under headers/ instead of under lib/ ? :)

No, I don't want it installed into headers/.
Because, I want it is be *very* clear that these files belongs to libbpf, when the system have libbpf installed, then they will not be located there.

I want to avoid other projects mispintreret and copy everything from headers/ directory.

You comment makes me realize that I've not been clear enough about the original intent with the 'headers/' directory.
All other/most projects have a direcory called 'include/' for their projects include/header files.
The intent with naming it 'headers/' was to keep the kernel headers in a separate directory, and then have an 'include/' directory with the projects own header files (in xdp-tutorial this was called 'common/', which should have been named include instead).

The intent was to have 'headers/' strictly contain the files need to compile BPF-progs, which the relevant headers copied from the kernel and the modified/compat headers like `compiler.h`, `err.h` and `perf-sys.h`. This would make it easier for other projects to understand or don't understand simply copy 'headers/' into their repos.

**Comment by netoptimizer** [comment]
Merge based on agreement with Toke on video chat

**Pull request merged**
