### PR TITLE
First pass at integration of AF_XDP-filter

### PR DESCRIPTION
**Pull request by tjcw**
Fix name

Pass thorugh unrecognised eth types

Already in namespace

### CODE REVIEW

**Comment by tjcw** [comment]
This test case does not run correctly with the current submodule libbpf (commit a6d7530cb7dff87ac1e64a540e63b67ddde2e0f9), but the corresponding test case as part of xdp-tutorial (	git@github.com:tjcw/xdp-tutorial.git commit d55ad94108d8c74de1992e03dd55df86081265fb ) does work with the 'latest' libbpf ( commit 1596a09b5de2a50ab8d44218fc29b6d42f886305 ) . I am attaching run logs from the failing and passing versions
[runns-failing.log](https://github.com/xdp-project/bpf-examples/files/10057101/runns-failing.log)
[runns-passing.log](https://github.com/xdp-project/bpf-examples/files/10057093/runns-passing.log)

**Comment by tjcw** [comment]
I just checked the behaviour running between 2 virtual machines on a machine, using the 'latest' libbpf. It works as expected
```
tjcw@tjcw-Standard-PC-Q35-ICH9-2009-1:~$ ping -c 5 192.168.122.44
PING 192.168.122.44 (192.168.122.44) 56(84) bytes of data.
64 bytes from 192.168.122.44: icmp_seq=2 ttl=64 time=0.906 ms
64 bytes from 192.168.122.44: icmp_seq=3 ttl=64 time=0.940 ms
64 bytes from 192.168.122.44: icmp_seq=4 ttl=64 time=0.774 ms
64 bytes from 192.168.122.44: icmp_seq=5 ttl=64 time=0.950 ms

--- 192.168.122.44 ping statistics ---
5 packets transmitted, 4 received, 20% packet loss, time 4034ms
rtt min/avg/max/mdev = 0.774/0.892/0.950/0.070 ms
tjcw@tjcw-Standard-PC-Q35-ICH9-2009-1:~$ 
```

**Comment by tohojo** [comment]
Well, please try to figure out why it's failing. Ideas:

- Enable libbpf logging and see which steps fails
- Bisect the libbpf versions to figure out which commit makes the difference

As for the code, you'll need to get rid of all the common_* stuff imported from the xdp-tutorial. Use the headers already in the top-level headers/ directory, and amend them as needed (in separate commits).

Also, please split up the series in easy-to-review chunks and write proper commit messages. And add a README file explaining what the example does.

**Comment by tjcw** [comment]
I will try the bisection, but why are you asking me to do that given that the 'bleeding edge' works ?
I thought I had it all as one commit which implements the example. I will write a README.

**Comment by tjcw** [comment]
Closing to replace with a PR with a README.md

**Pull request closed without merging**
