### PR TITLE
Cleanups for bpf-examples

### PR DESCRIPTION
**Pull request by netoptimizer**
Some cleanups that @tohojo should review, please.

### CODE REVIEW

**Comment by tohojo** [comment]
Rather than the first commit, I figure I'll just update the libbpf version. What's the stgit issue with the dirty subdir?

**Comment by tohojo** [comment]
Right, updated the libbpf version so encap-forward builds out of the box now...

**Comment by netoptimizer** [comment]
The dirty subdir issue looks like this:
```
[bpf-examples]$ git diff
diff --git a/lib/libbpf b/lib/libbpf
--- a/lib/libbpf
+++ b/lib/libbpf
@@ -1 +1 @@
-Subproject commit bbe442da7a5e89b1f8bdbac4968f09e05b24bf5d
+Subproject commit bbe442da7a5e89b1f8bdbac4968f09e05b24bf5d-dirty
```

This breaks the `stg import` command, as it detect git tree have "local changes" it will not allow the import of the patch:
```
[bpf-examples]$ stg import patches-mybranch01/01-cleanup-makefile-whitespace 
Checking for changes in the working directory ... done
stg import: local changes in the tree. Use "refresh" or "reset --hard"
```

**Comment by tohojo** [comment]
Jesper Dangaard Brouer <notifications@github.com> writes:

> The dirty subdir issue looks like this:
> ```
> [bpf-examples]$ git diff
> diff --git a/lib/libbpf b/lib/libbpf
> --- a/lib/libbpf
> +++ b/lib/libbpf
> @@ -1 +1 @@
> -Subproject commit bbe442da7a5e89b1f8bdbac4968f09e05b24bf5d
> +Subproject commit bbe442da7a5e89b1f8bdbac4968f09e05b24bf5d-dirty
> ```
>
> This breaks the `stg import` command, as it detect git tree have "local changes" it will not allow the import of the patch:
> ```
> [bpf-examples]$ stg import patches-mybranch01/01-cleanup-makefile-whitespace 
> Checking for changes in the working directory ... done
> stg import: local changes in the tree. Use "refresh" or "reset --hard"
> ```

Ah, right. Well, you can also fix this by issuing:

`echo src/root/ >> .git/modules/lib/libbpf/info/exclude`

wondering if it's not easier to just do that instead of moving things
about (assuming stgit also respects this)?

**Comment by netoptimizer** [comment]
> @tohojo : Right, updated the libbpf version so encap-forward builds out of the box now...

First it was not working for me... after calling `./configure` then it worked... which was kind of strange.

**Comment by tohojo** [comment]
Toke Høiland-Jørgensen <toke@toke.dk> writes:

> Jesper Dangaard Brouer <notifications@github.com> writes:
>
>> The dirty subdir issue looks like this:
>> ```
>> [bpf-examples]$ git diff
>> diff --git a/lib/libbpf b/lib/libbpf
>> --- a/lib/libbpf
>> +++ b/lib/libbpf
>> @@ -1 +1 @@
>> -Subproject commit bbe442da7a5e89b1f8bdbac4968f09e05b24bf5d
>> +Subproject commit bbe442da7a5e89b1f8bdbac4968f09e05b24bf5d-dirty
>> ```
>>
>> This breaks the `stg import` command, as it detect git tree have "local changes" it will not allow the import of the patch:
>> ```
>> [bpf-examples]$ stg import patches-mybranch01/01-cleanup-makefile-whitespace 
>> Checking for changes in the working directory ... done
>> stg import: local changes in the tree. Use "refresh" or "reset --hard"
>> ```
>
> Ah, right. Well, you can also fix this by issuing:
>
> `echo src/root/ >> .git/modules/lib/libbpf/info/exclude`
>
> wondering if it's not easier to just do that instead of moving things
> about (assuming stgit also respects this)?

Ah, or maybe we should just add 'ignore = dirty' to the libbpf dir in
.gitmodules - that can actually be committed to the repository whereas
putting things in .git/modules/lib/libbpf/info/exclude is only local to
one checked-out repository...

**Comment by netoptimizer** [comment]
I think it is valuable to have it outside in directory `lib/libbpf-install/`, because it helps people understand the connection.

**Comment by netoptimizer** [comment]
Closing this as PR #8 is my updated PR

**Pull request closed without merging**
